# Generated by Django 5.2 on 2025-05-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0003_ride_passengers_alter_ride_driver_alter_ride_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
