# Generated by Django 5.2 on 2025-05-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0004_ride_check_in_time_ride_check_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='distance_km',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
