# Generated by Django 5.2 on 2025-05-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0005_ride_distance_km_alter_ride_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='distance_km',
            field=models.FloatField(default=0),
        ),
    ]
